use std::fs;

fn main() {
    // The icon set is embedded at compile time (window/tray icon via
    // `generate_context!`, exe resource via winres). `tauri_build` only watches
    // tauri.conf.json, so without this a changed icon leaves a stale build.
    println!("cargo:rerun-if-changed=icons");
    println!("cargo:rerun-if-changed=src/lib.rs");

    // With an app manifest, Tauri refuses every app command a window's
    // capability does not allow. Without one, every window — the quick-action
    // popup included — could call all of them.
    let commands = app_commands();
    write_all_commands_set(commands);
    if let Err(error) = tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(commands)),
    ) {
        panic!("{error:#}");
    }
}

/// Every command `generate_handler!` in `src/lib.rs` registers.
///
/// Read from the one list that registers them rather than kept as a second
/// copy: a command missing here would be refused for every window, and one
/// listed here but not registered would be a permission for nothing.
fn app_commands() -> &'static [&'static str] {
    const OPEN: &str = "generate_handler![";
    let source: &'static str = Box::leak(
        fs::read_to_string("src/lib.rs")
            .expect("read src/lib.rs")
            .into_boxed_str(),
    );
    let start = source.find(OPEN).expect("generate_handler! in src/lib.rs") + OPEN.len();
    let end = start
        + source[start..]
            .find(']')
            .expect("closing ] of generate_handler!");
    let commands: Vec<&'static str> = source[start..end]
        .split(',')
        .map(str::trim)
        .filter(|path| !path.is_empty())
        .map(|path| path.rsplit("::").next().unwrap_or(path))
        .collect();
    for command in &commands {
        assert!(
            command
                .chars()
                .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_'),
            "build.rs reads generate_handler! as plain `path::command,` entries and cannot \
             parse {command:?} — keep attributes and comments out of that list",
        );
    }
    assert!(
        !commands.is_empty(),
        "generate_handler! in src/lib.rs lists no commands"
    );
    Box::leak(commands.into_boxed_slice())
}

/// The permission set `capabilities/default.json` grants the main window.
///
/// The main window is the host layer and reaches every command; a narrower
/// window lists its own commands in its capability instead. Generated for the
/// same reason as the command list: a new command must not need a third edit.
fn write_all_commands_set(commands: &[&str]) {
    let permissions: String = commands
        .iter()
        .map(|command| format!("  \"allow-{}\",\n", command.replace('_', "-")))
        .collect();
    let toml = format!(
        "# Generated by build.rs from generate_handler! in src/lib.rs - DO NOT EDIT.\n\n\
         [[set]]\n\
         identifier = \"app-commands\"\n\
         description = \"Every command the app registers.\"\n\
         permissions = [\n{permissions}]\n"
    );
    let path = "permissions/autogenerated/app-commands.toml";
    // Only on change: `permissions/` is watched, so rewriting it on every run
    // would make every build re-run this script.
    if fs::read_to_string(path).ok().as_deref() != Some(toml.as_str()) {
        fs::create_dir_all("permissions/autogenerated").expect("create permissions dir");
        fs::write(path, toml).expect("write the app-commands permission set");
    }
}
