//! The Widget-Wizard system prompt.
//!
//! Neither the package format nor the house style is restated here.
//! `docs/runtime-packages.md` and `docs/DESIGN.md` are embedded verbatim with
//! `include_str!`, so the documents a human reads and the instructions a model
//! gets are the same bytes. Two hand-maintained copies of a rule drift, and the
//! drift shows up as widgets that fail validation, or look wrong, for reasons
//! nobody can explain.

/// The package format, embedded from the doc at compile time.
const PACKAGE_DOC: &str = include_str!("../../../docs/runtime-packages.md");

/// The house style, embedded the same way and for the same reason.
const DESIGN_DOC: &str = include_str!("../../../docs/DESIGN.md");

/// The other package format: a widget that reads from a connected provider.
const CONTRACT_DOC: &str = include_str!("../../../docs/contract-packages.md");

/// What each provider offers, generated by `npm run build:provider-doc` from the
/// definitions under `extensions/*/provider.ts`.
///
/// EMBEDDED, NOT PASSED IN. `wizard_complete` keeps the system prompt out of the
/// caller's hands so a caller cannot loosen the rules the output is validated
/// against; a rendered block arriving from the webview would be exactly that.
/// The caller names a provider instead, and the choice of *which* block is
/// spliced happens at run time while the content of every block does not.
///
/// `providerSchemaDoc.assert.ts` fails the build when this file and the
/// providers disagree.
const PROVIDER_BLOCKS: &str = include_str!("provider-blocks.json");

/// The block for one provider, or none when the caller named nothing this host
/// knows.
///
/// Parsed per call rather than cached: it happens once per authoring turn,
/// beside a network round trip to a model, and a `OnceLock` here would buy
/// nothing but a second thing to reason about.
pub fn provider_block(provider: Option<&str>) -> Option<String> {
    let id = provider?;
    let map: serde_json::Map<String, serde_json::Value> =
        serde_json::from_str(PROVIDER_BLOCKS).ok()?;
    map.get(id)?.as_str().map(str::to_string)
}

/// The blocks for several providers, in the order they were ticked.
///
/// An id nobody ships is skipped rather than rendered as an empty heading — a
/// heading with nothing under it reads to the model as "this account has no
/// queries", which is a worse answer than not mentioning it.
pub fn provider_blocks(providers: &[String]) -> Vec<String> {
    providers
        .iter()
        .filter_map(|id| provider_block(Some(id)))
        .collect()
}

/// The generated provider ids, kept beside the schema blocks so MCP and the
/// Wizard cannot advertise different contract-package capabilities.
#[allow(dead_code)]
pub fn provider_ids() -> Vec<String> {
    let Ok(map) =
        serde_json::from_str::<serde_json::Map<String, serde_json::Value>>(PROVIDER_BLOCKS)
    else {
        return Vec::new();
    };
    let mut ids: Vec<String> = map.keys().cloned().collect();
    ids.sort();
    ids
}

/// Exact generated provider schema document used by the read-only MCP resource.
pub fn provider_schema_document() -> String {
    PROVIDER_BLOCKS.to_string()
}

/// Marker the model wraps each generated file in.
///
/// A fenced block with a `path=` attribute rather than one big JSON object:
/// HTML and JS are full of quotes and newlines, and a model that has to escape
/// them into JSON gets it wrong often enough to matter. A fence needs no
/// escaping at all.
pub const FILE_FENCE_HINT: &str = "```<lang> path=<package-relative path>";

/// Full system prompt for a widget-authoring turn.
pub fn system_prompt() -> String {
    format!(
        r#"You write Kavibay runtime widget packages for people who do not code.

The person describes a widget in plain language. You reply with the complete
set of files for one package, and nothing else that looks like a file.

# Output format

Emit each file as a fenced code block whose info string carries its
package-relative path:

{FILE_FENCE_HINT}

For example:

```json path=manifest.json
{{ "id": "water-tracker", ... }}
```

```html path=ui/index.html
<!doctype html>...
```

A widget is behaviour, not a screen. Before you write markup, decide what state
it keeps, what it computes from that state, and when it saves. A layout whose
buttons do nothing is not a half-finished widget, it is a picture of one — and
it is the most common way this goes wrong, so check your own output for it
before you answer.

The rules for your reply:

- **An answer without file blocks is not an answer.** The explanation is the
  smaller half of the turn and the files are the turn itself, so never stop
  after describing what you would build — that reads as a finished widget and
  delivers nothing. If you truly cannot build what was asked, say so in one
  sentence and build the closest thing you can; but never describe a widget you
  did not emit.
- Emit the complete file set **unless the message says otherwise**. For a
  widget that already exists the host may tell you to return only what you
  changed; do that when it does, and leave the rest out.
- **A file you omit is kept, never deleted.** To remove one, emit its block
  with `deleted=true` in the info string and an empty body:
  ```json path=api.json deleted=true
  ```
  Silence is not a deletion — the host cannot tell "I did not touch it" from
  "I meant to remove it", so it keeps the file.
- `manifest.json` is always present, and its `id` must equal the package id you
  are told to use.
- Write one or two sentences of plain-language explanation before the blocks.
  No prose between or after them.
- Never claim a widget does something the files do not do.
- Anything the person can change must survive a reload. Use `kavibay.storage`
  and declare `storage.instance`; `localStorage` throws in this sandbox.
- Load the bridge with `<script src="@kavibay/runtime.js"></script>` before your
  own script. The host serves it. Never emit a `kavibay-runtime.js` of your own —
  a stand-in defines nothing and every call throws on the first click.
- Draw from defaults immediately and reconcile when storage answers. Never gate
  the interface on a reply that may not come.

# Images

The person may attach a screenshot, a photo or a mockup. Build to what you see
in it — match the layout, the wording and the colours unless they say otherwise.
If an image is unreadable or shows something you cannot build inside the
sandbox, say so plainly instead of guessing.

# What you can and cannot rely on

The package runs in a sandboxed iframe with no access to other widgets and no
access to the machine. It reaches the network only through the endpoints it
declares — that is the normal way to build a widget that shows live data, not a
last resort. If a request needs something the format cannot express, say so
plainly in your explanation and build the part that is possible — never invent
sample data and present it as real.

Keep the UI small. These are desktop widgets, often 260x200; a layout that
needs scrolling to read one number is a failed widget.

# Network and credentials

`fetch` and `XMLHttpRequest` do not exist here (`connect-src 'none'`). Instead
you declare every request in `api.json` and call it by id; the host builds it,
sends it, and hands you the response. Three things move together — a widget that
reads live data has all three or none:

```json path=manifest.json
{{ "id": "pr-inbox", "permissions": ["storage.instance", "network.declared"] }}
```

```json path=api.json
{{
  "schemaVersion": 1,
  "endpoints": [
    {{
      "id": "pulls",
      "description": "Reads the open pull requests of one GitHub repository.",
      "method": "GET",
      "url": "https://api.github.com/repos/{{owner}}/{{repo}}/pulls",
      "path": {{
        "owner": {{ "type": "string", "required": true, "charset": "alnumDash" }},
        "repo": {{ "type": "string", "required": true, "charset": "alnumDot" }}
      }},
      "query": {{ "state": {{ "type": "const", "value": "open" }} }},
      "credential": "githubPat",
      "cache": {{ "ttlSeconds": 300 }},
      "rate": {{ "minIntervalSeconds": 60 }}
    }}
  ]
}}
```

```js path=app.js
const res = await kavibay.http("pulls", {{ owner, repo }});
if (!res.ok) return showError(res.code);   // never rejects — always branch on ok
render(res.data);
```

What goes wrong here, in the order it goes wrong:

- **`description` is consent text.** The person reads it in a dialog and decides
  whether to enable you from it. Write what the request reads and from whom, in
  their words. It is the one string in the package written for someone else.
- **A credential is requested, never held.** Set `credential` to a type the host
  knows — `githubPat`, `linearApi`, `notionApi`, `n8nApi`, `spotifyOAuth2`, `fitbitOAuth2`, `anthropicApi`, `openaiApi`, `cloudflareWorkersAi` — and
  it attaches the secret to your declared request. You never see the token. An
  `Authorization` header in `headers` fails validation; do not reach for one.
- **The url is fixed.** `{{name}}` fills one whole path segment and nothing else.
  Everything variable is a declared parameter. A url you build by concatenating
  strings is a package that will not load.
- **Four states, not one.** Not-configured, loading, error and empty each need a
  screen. A widget that renders only the happy path is an empty box on the day
  the token expires.
- **Say which credential is missing.** On `credential_not_configured` or
  `credential_not_granted`, name it and point at Settings → Credentials. "Error"
  tells the person nothing they can act on.

# The package format

{PACKAGE_DOC}

# House style

Widgets sit on the user's desktop next to a dozen others. A widget that ignores
this reads as pasted on, however well it works — so follow it unless the person
asks for something else, and say so when you depart from it.

{DESIGN_DOC}
"#
    )
}

/// System prompt for a widget that reads from a connected provider.
///
/// A separate prompt rather than a paragraph inside the other one. The two
/// formats disagree about nearly everything a model has to get right — the
/// runtime it loads, what it may not draw, how it gets data, whether it may
/// write — and a single prompt holding both is a prompt that produces hybrids:
/// a `manifest.json` with `api.json` fields in it, `kavibay.storage` beside
/// `ctx.data`. Each one is valid-looking and loads as neither.
///
/// The caller picks, from what the widget needs rather than from what the
/// person said: a connected account means this one.
pub fn contract_system_prompt(providers: &[String]) -> String {
    // Named rather than inlined so the prompt reads the same whether or not a
    // provider was picked: none means no section, not an empty heading.
    let blocks = provider_blocks(providers);
    let provider_section = if blocks.is_empty() {
        String::new()
    } else {
        // Singular and plural are two headings rather than one hedged one. The
        // model is being told how many accounts it has, and "the providers this
        // widget reads from" above a single block invites it to invent a
        // second.
        let heading = if blocks.len() == 1 {
            "# The provider this widget reads from"
        } else {
            "# The providers this widget reads from\n\nUse each one for what it \
             actually has. Do not fetch from one what the other declares."
        };
        format!("\n{heading}\n\n{}\n", blocks.join("\n\n"))
    };
    format!(
        r#"You write Kavibay contract widget packages for people who do not code.

The person describes a widget in plain language. You reply with the complete
set of files for one package, and nothing else that looks like a file.

# Output format

Emit each file as a fenced code block whose info string carries its
package-relative path:

{FILE_FENCE_HINT}

For example:

```json path=manifest.json
{{ "name": "room-summary", ... }}
```

The rules for your reply:

- **An answer without file blocks is not an answer.** Never stop after
  describing what you would build — that reads as a finished widget and delivers
  nothing.
- **`manifest.json` is always present, and its `name` must equal the package id
  you are told to use.** Not `id` — that is the other format's field, and a
  contract manifest naming itself with one is rejected before it is written.
- Write one or two sentences of plain-language explanation before the blocks.
  No prose between or after them.
- Emit the complete file set **unless the message says otherwise**. For a
  widget that already exists the host may tell you to return only what you
  changed; do that when it does, and leave the rest out.
- **A file you omit is kept, never deleted.** To remove one, emit its block
  with `deleted=true` in the info string and an empty body:
  ```json path=api.json deleted=true
  ```
  Silence is not a deletion — the host cannot tell "I did not touch it" from
  "I meant to remove it", so it keeps the file.
- **Ask for the fewest accounts that work.** The person is shown the accounts
  you named and ticks the ones they allow. An account they do not tick, you do
  not get — and one they have not connected puts a prompt in front of your
  widget.
- **No provider of your own, no commands, no palette actions.** Provider
  actions listed for this account may be called with
  `ctx.providers[id].action` — **declare every one you call in its provider
  entry's `actions`**. The person decides separately whether you may change
  things, and the host refuses an action you did not declare.
- **Write each provider as an entry: `{{ "id", "queries", "actions" }}`.** List
  every query you call with `query` or `subscribe` in `queries`, and nothing
  you do not: it is what the person is shown when they approve the widget.
- **Never draw a spinner, an error, a retry or a connect screen.** The host
  draws all of those around your widget. Yours would be the second one.

# The format

{CONTRACT_DOC}
{provider_section}
# House style

Widgets sit on the user's desktop next to a dozen others. A widget that ignores
this reads as pasted on, however well it works — so follow it unless the person
asks for something else, and say so when you depart from it.

{DESIGN_DOC}
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The document the model reads teaches the format the host enforces.
    ///
    /// THIS IS THE TEST THAT WAS MISSING. `requires.provider` became
    /// `requires.providers` and `permissions` became a map keyed by provider
    /// id, across the contract, the host, the registry and the stored grants —
    /// and `docs/contract-packages.md`, which is spliced into this prompt
    /// verbatim, still described the old shape. Everything compiled, 118 assert
    /// files and 355 Rust tests passed, and the first widget a person generated
    /// was refused at load for using the spelling the prompt had just taught
    /// it. The doc was embedded precisely so there would be no second copy to
    /// drift; embedding stops a copy from existing, it does not stop the
    /// original from going stale.
    ///
    /// The negative half matters more than the positive one: the old spelling
    /// must be *absent*, not merely accompanied by the new one. A prompt
    /// showing both teaches neither.
    #[test]
    fn the_contract_prompt_teaches_the_format_the_host_accepts() {
        let prompt = contract_system_prompt(&["kavibay.tado/tado".to_string()]);

        assert!(
            prompt.contains(r#""providers": [{ "id": "kavibay.tado/tado", "queries": ["#),
            "the worked manifest must use the list of provider entries",
        );
        assert!(
            !prompt.contains(r#""queries": { "kavibay."#)
                && !prompt.contains(r#""actions": { "kavibay."#),
            "and must not still show queries or actions as maps beside the list, which the loader refuses",
        );
        assert!(
            !prompt.contains(r#""requires": { "provider":"#),
            "and must not still show the singular one, which the loader refuses",
        );
        assert!(
            prompt.contains("ctx.providers["),
            "the widget-side API is a map keyed by provider id",
        );
        assert!(
            !prompt.contains("ctx.provider."),
            "and the old single handle must not appear in any example",
        );
        assert!(
            prompt.contains("More than one provider"),
            "and a widget reading two accounts has to be shown, not left to be inferred",
        );
        assert!(
            !prompt.contains("\"permissions\""),
            "the permissions field is gone (§27); a prompt still showing it teaches a manifest key \
             the loader rejects as unknown",
        );
        // The chained shape — search, then fetch one result by id — is the
        // ordinary REST pattern, and the model concluded it was impossible
        // because the docs said a placeholder fills a *whole* segment. It does
        // not any more, and the prompt has to carry the worked example or the
        // model keeps answering "not possible" to something that is.
        // Per-instance settings are free — the host builds the form from the
        // schema — and the model was inventing its own token prompts because
        // the prompt showed `configuration` only as a provider-backed select.
        assert!(
            prompt.contains("Settings the person can change later"),
            "the prompt must say a widget can declare its own settings",
        );
        assert!(
            prompt.contains("gear in the widget menu"),
            "and that they stay reachable after the first answer",
        );
        assert!(
            prompt.contains("Two calls, where the second needs the first"),
            "the prompt must show how to use a result from one endpoint in the next",
        );
        assert!(
            prompt.contains("@{uid}"),
            "including a placeholder inside a segment, which is the part that was refused",
        );
        assert!(
            prompt.contains("is just a parameter"),
            "and that an API wanting ?token= takes a normal parameter, not a credential",
        );
        assert!(
            prompt.contains("ctx.endpoint("),
            "a widget must be told it can reach an API no provider covers, or it answers              \"not possible\" to a request that is",
        );
        assert!(
            prompt.contains("ctx.providers[id].action"),
            "and the model must be told it can call provider actions, or a playlist widget \
             opens a URL instead of playing",
        );
        assert!(
            prompt.contains("in its provider\n  entry's `actions`"),
            "and that each one is declared, or the host refuses the first button it draws",
        );
        assert!(
            prompt.contains(r#"`{ "id", "queries", "actions" }`"#),
            "and that the queries it reads are named, since that list is what the person is shown",
        );
    }

    /// Two ticked accounts reach the model as two blocks under one heading.
    ///
    /// The whole point of the multi-select: a widget showing room temperatures
    /// with the outdoor temperature under them needs tado° and Open-Meteo, and
    /// a prompt carrying one of them produces a widget that invents the other.
    #[test]
    fn every_ticked_provider_is_spliced() {
        let prompt = contract_system_prompt(&[
            "kavibay.tado/tado".to_string(),
            "kavibay.weather/weather".to_string(),
        ]);

        assert!(
            prompt.contains("The providers this widget reads from"),
            "the heading is plural when there is more than one",
        );
        // A query name from each block, so this fails if either was dropped
        // rather than merely if the heading changed.
        assert!(prompt.contains("zoneStates"), "tado°'s queries are there");
        assert!(prompt.contains("places"), "and Open-Meteo's");
    }

    /// One account keeps the singular heading.
    ///
    /// Not cosmetic: "the providers this widget reads from" above a single
    /// block is an invitation to invent a second one.
    #[test]
    fn one_ticked_provider_keeps_the_singular_heading() {
        let prompt = contract_system_prompt(&["kavibay.tado/tado".to_string()]);
        assert!(prompt.contains("# The provider this widget reads from"));
        assert!(!prompt.contains("# The providers this widget reads from"));
    }

    /// An id nobody ships is skipped, and the ones beside it still arrive.
    #[test]
    fn an_unknown_id_does_not_take_its_neighbours_down() {
        let prompt = contract_system_prompt(&[
            "kavibay.invented/nope".to_string(),
            "kavibay.tado/tado".to_string(),
        ]);
        assert!(
            prompt.contains("zoneStates"),
            "the real one is still spliced"
        );
        assert!(
            !prompt.contains("kavibay.invented/nope"),
            "and the invented one leaves no heading behind",
        );
    }

    /// A picked provider reaches the model, and an unpicked one leaves no trace.
    ///
    /// Both halves matter. The first is the feature; the second is what keeps a
    /// runtime-package turn from being told about accounts it cannot use.
    #[test]
    fn the_picked_provider_is_spliced_and_nothing_else_is() {
        let with_provider = contract_system_prompt(&["kavibay.tado/tado".to_string()]);
        assert!(with_provider.contains("The provider this widget reads from"));
        // A phrase only the generated block carries — `zoneStates` alone would
        // also match the format document's worked example.
        assert!(with_provider.contains("Use only the queries and actions below"));

        let without = contract_system_prompt(&[]);
        assert!(!without.contains("The provider this widget reads from"));
        assert!(!without.contains("Use only the queries and actions below"));
    }

    /// Playback writes belong in the schema the Wizard is shown, same as queries.
    #[test]
    fn spotify_prompt_offers_play() {
        let prompt = contract_system_prompt(&["kavibay.spotify/spotify".to_string()]);
        assert!(
            prompt.contains("`play`"),
            "play must be offered so a playlist list can start on the active device",
        );
        assert!(
            prompt.contains("playlistId"),
            "and play must take a playlist id, not only resume",
        );
    }

    /// An id nobody ships must not produce an empty heading that reads as though
    /// a provider was described and had nothing to say.
    #[test]
    fn an_unknown_provider_adds_no_section() {
        let prompt = contract_system_prompt(&["kavibay.invented/nope".to_string()]);
        assert!(!prompt.contains("The provider this widget reads from"));
    }

    /// The embedded blocks are generated; this catches the quiet failure where
    /// the file is present but says nothing.
    #[test]
    fn the_embedded_blocks_are_not_empty() {
        assert!(provider_block(Some("kavibay.tado/tado")).is_some_and(|b| b.contains("zones")));
    }

    /// The prompt is only correct as long as it really carries the format doc.
    /// If the doc moves, `include_str!` fails the build — this catches the
    /// quieter failure where it is present but empty.
    #[test]
    fn the_prompt_embeds_the_package_documentation() {
        let prompt = system_prompt();
        assert!(prompt.len() > 4000, "doc did not make it into the prompt");
        assert!(prompt.contains("manifest.json"));
        assert!(
            prompt.contains("path=manifest.json"),
            "the output format must be shown, not just described"
        );
    }

    /// The contract prompt has to carry the rules that fail silently, because a
    /// model that misses one produces a widget which looks finished, loads, and
    /// does nothing — with no error in any place a user looks.
    #[test]
    fn the_contract_prompt_carries_the_silent_rules() {
        let prompt = contract_system_prompt(&[]);
        assert!(prompt.len() > 4000, "the contract doc did not make it in");

        for rule in [
            // Finding 17: a module script never loads under an opaque origin.
            "type=\"module\"",
            // Finding 18: the submit event is skipped, not prevented.
            "<form>",
            // An opaque origin has no localStorage; ctx.data is the way.
            "localStorage",
            // The runtime it must load, which is not the other format's.
            "@kavibay/contract.js",
            // The mount point, without which the frame just stays empty.
            "kavibay-widget",
            // A generated widget writes `<a href>` for "open this issue". The
            // frame cannot navigate, so the prompt has to say the host opens
            // it — or the model ships a link that looks clickable and is dead.
            "openExternal",
        ] {
            assert!(
                prompt.contains(rule),
                "the contract prompt must mention {rule}"
            );
        }
    }

    /// A generated Linear widget shipped "Open in Linear" as `<a href>` and
    /// the click did nothing: the frame has no navigation, and telling the
    /// model to use a click handler instead is a rule it keeps missing. The
    /// host now intercepts the click, so the prompt has to teach the markup
    /// that actually works — and must not still say the link is dead.
    #[test]
    fn the_contract_prompt_teaches_that_a_provider_link_opens() {
        let prompt = contract_system_prompt(&[]);
        assert!(
            prompt.contains("<a href=\"${issue.url}\">"),
            "the worked markup is an <a href> with a provider url, not a click handler",
        );
        assert!(
            prompt.contains("ctx.openExternal.open"),
            "a button still has the explicit call",
        );
        assert!(
            !prompt.contains("An `<a href>` does nothing"),
            "the old rule contradicts the intercept and would teach a dead control",
        );
    }

    /// The two formats disagree about nearly everything, and a model given both
    /// at once produces hybrids that load as neither. Whichever prompt is built,
    /// the other format's runtime must not be in it.
    #[test]
    fn the_two_prompts_do_not_bleed_into_each_other() {
        assert!(
            !contract_system_prompt(&[]).contains("kavibay.storage"),
            "the contract prompt must not offer the runtime package storage API"
        );
        assert!(
            !system_prompt().contains("@kavibay/contract.js"),
            "the runtime package prompt must not offer the contract runtime"
        );
    }

    /// If the design doc stops reaching the model, generated widgets quietly
    /// drift out of the house style — a failure with no error attached to it.
    /// Widgets that look right and do nothing were the common failure, so the
    /// working shape has to reach the model, not just a mention of the API.
    #[test]
    fn the_prompt_teaches_state_and_storage() {
        let prompt = system_prompt();
        assert!(prompt.contains("kavibay.storage"));
        assert!(
            prompt.contains("localStorage"),
            "the sandbox has none, and a model that assumes otherwise ships a widget that forgets"
        );
        assert!(
            prompt.contains("storage.instance"),
            "the permission is easy to omit"
        );
        assert!(
            prompt.contains("function render()"),
            "a worked example beats a description of one"
        );
    }

    /// A generated widget shipped an "add repository" form whose submit handler
    /// could never run: the frame is sandboxed `allow-scripts`, so no `submit`
    /// event fires and the browser logs nothing. `<form>` + submit button is the
    /// obvious way to write an input with a button, which makes it exactly the
    /// trap a model walks into unless the prompt says otherwise.
    #[test]
    fn the_prompt_rules_out_controls_the_sandbox_kills() {
        let prompt = system_prompt();
        assert!(
            prompt.contains("No form submission"),
            "the dead-control failure has to be named, not left to be discovered"
        );
        assert!(
            prompt.contains("click"),
            "naming the ban without naming the replacement leaves the model stuck"
        );
        assert!(
            prompt.contains("No pop-ups or navigation"),
            "a widget cannot open a link, and a link that does nothing looks broken"
        );
    }

    /// The TypeScript side merges an answer onto the package instead of
    /// replacing it, so a file the model leaves out is kept. That only works if
    /// the model has been told the same thing — and the failure is silent in
    /// both directions: an unchanged prompt makes it rewrite whole packages for
    /// nothing, and a half-changed one makes it drop files by omitting them.
    #[test]
    fn both_prompts_say_that_an_omitted_file_is_kept() {
        for (name, prompt) in [
            ("runtime", system_prompt()),
            ("contract", contract_system_prompt(&[])),
        ] {
            assert!(
                prompt.contains("A file you omit is kept, never deleted"),
                "{name}: omission must not read as deletion — mergeGeneratedFiles keeps it"
            );
            assert!(
                prompt.contains("deleted=true"),
                "{name}: the only way left to remove a file has to be named"
            );
            assert!(
                !prompt.contains("a file you\n  omit is a file you deleted"),
                "{name}: the old rule contradicts the merge and must be gone"
            );
            assert!(
                prompt.contains("unless the message says otherwise"),
                "{name}: the partial form is granted per turn, so the prompt must defer to it"
            );
        }
    }

    /// The observed failure was a model that wrote its two sentences of
    /// explanation and stopped — a reply that reads finished, parses to zero
    /// files, and reaches the person as "The answer contained no files."
    /// The prose instruction alone invites it, so the counterweight has to be
    /// present and has to come first.
    #[test]
    fn the_prompt_forbids_an_answer_without_files() {
        let prompt = system_prompt();
        assert!(
            prompt.contains("An answer without file blocks is not an answer"),
            "the rule that catches a model which describes instead of building"
        );
        let rule = prompt
            .find("An answer without file blocks")
            .expect("rule must be present");
        let prose_instruction = prompt
            .find("plain-language explanation")
            .expect("prose instruction must be present");
        assert!(
            rule < prose_instruction,
            "the files-are-mandatory rule must precede the write-an-explanation rule, \
             or the model satisfies the explanation and stops"
        );
    }

    /// Without a worked declaration in front of it, the model treats the network
    /// as unavailable and ships a widget full of invented numbers — the failure
    /// is invisible, because such a widget looks finished. The reference lives in
    /// `PACKAGE_DOC`; what this asserts is that the prompt also *reaches* for it.
    #[test]
    fn the_prompt_teaches_declared_network() {
        let prompt = system_prompt();
        assert!(
            prompt.contains("network.declared") && prompt.contains("path=api.json"),
            "the permission and the file it requires must appear together"
        );
        assert!(
            prompt.contains("kavibay.http(\"pulls\""),
            "a worked call beats a description of one"
        );
        assert!(
            prompt.contains("branch on ok"),
            "http() resolves on provider errors; a model that assumes throw ships no error state"
        );
        assert!(
            prompt.contains("githubPat")
                && prompt.contains("linearApi")
                && prompt.contains("n8nApi")
                && prompt.contains("notionApi")
                && prompt.contains("spotifyOAuth2")
                && prompt.contains("fitbitOAuth2"),
            "a real credential type id, so the model does not invent one that fails validation"
        );
        assert!(
            prompt.contains("Authorization"),
            "the header is the reflex to unlearn — declaring it fails the package"
        );
        // A generated GitHub widget failed on exactly this: `review-requests`.
        // Kebab-case is the natural spelling for an id and the validator refuses
        // it, so the rule has to be in front of the model, not only in the code.
        assert!(
            prompt.contains("No dashes"),
            "the endpoint id charset must reach the model, or it writes kebab-case"
        );
    }

    #[test]
    fn the_prompt_embeds_the_design_guidance() {
        let prompt = system_prompt();
        assert!(!DESIGN_DOC.is_empty());
        assert!(prompt.contains("House style"));
        assert!(
            prompt.contains("rgba(232, 232, 234, 0.92)"),
            "the concrete colours must reach the model, not just the headings"
        );
        assert!(
            prompt.contains("background: transparent"),
            "the one rule a package cannot get wrong is the transparent body"
        );
    }
}
