//! GENERATED by `npm run build:provider-doc`. Do not edit.
//!
//! Source: `extensions/*/provider.ts`. Checked by
//! `scripts/providerSchemaDoc.assert.ts`, which fails the build when this file
//! and the definitions disagree — so a provider added in TypeScript and
//! forgotten here cannot ship, and neither can a host added here and to nothing
//! else.
//!
//! Compiled in and PR-reviewed, exactly as when it was written by hand. What
//! changed is that one fact is now stated once.

use crate::extension_providers::{HostRule, ProviderDef};

pub const PROVIDERS: &[ProviderDef] = &[
    ProviderDef {
        id: "kavibay.calendar/calendar",
        host_rule: HostRule::Exact(&["www.googleapis.com", "oauth2.googleapis.com"]),
        credential_type: Some("googleCalendarOAuth2"),
        image_hosts: &[],
        link_hosts: &["meet.google.com", "calendar.google.com"],
    },
    ProviderDef {
        id: "kavibay.fitbit/fitbit",
        host_rule: HostRule::Exact(&["api.fitbit.com"]),
        credential_type: Some("fitbitOAuth2"),
        image_hosts: &[],
        link_hosts: &[],
    },
    ProviderDef {
        id: "kavibay.github/github",
        host_rule: HostRule::Exact(&["api.github.com"]),
        credential_type: Some("githubPat"),
        image_hosts: &[],
        link_hosts: &["github.com"],
    },
    ProviderDef {
        id: "kavibay.linear/linear",
        host_rule: HostRule::Exact(&["api.linear.app"]),
        credential_type: Some("linearApi"),
        image_hosts: &[],
        link_hosts: &["linear.app"],
    },
    ProviderDef {
        id: "kavibay.n8n/n8n",
        host_rule: HostRule::FromCredential { field: "origin" },
        credential_type: Some("n8nApi"),
        image_hosts: &[],
        link_hosts: &[],
    },
    ProviderDef {
        id: "kavibay.notion/notion",
        host_rule: HostRule::Exact(&["api.notion.com"]),
        credential_type: Some("notionApi"),
        image_hosts: &[],
        link_hosts: &["www.notion.so", "notion.so"],
    },
    ProviderDef {
        id: "kavibay.spotify/spotify",
        host_rule: HostRule::Exact(&["api.spotify.com"]),
        credential_type: Some("spotifyOAuth2"),
        image_hosts: &[
            "i.scdn.co",
            "mosaic.scdn.co",
            "image-cdn-ak.spotifycdn.com",
            "image-cdn-fa.spotifycdn.com",
        ],
        link_hosts: &["open.spotify.com"],
    },
    ProviderDef {
        id: "kavibay.tado/tado",
        host_rule: HostRule::Exact(&["my.tado.com", "auth.tado.com"]),
        credential_type: Some("tadoOAuth2"),
        image_hosts: &[],
        link_hosts: &[],
    },
    ProviderDef {
        id: "kavibay.weather/weather",
        host_rule: HostRule::Exact(&["geocoding-api.open-meteo.com", "api.open-meteo.com", "air-quality-api.open-meteo.com"]),
        credential_type: None,
        image_hosts: &[],
        link_hosts: &[],
    },
];
