/**
 * Shared knowledge about the built contract guest, so the build step and the
 * guard cannot disagree about what "up to date" means.
 */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

export const TARGET = join(root, "sdk", "contract-guest", "kavibay-contract-guest.js");

/**
 * Everything the bundle is built from. Types are erased, so only the two files
 * carrying runtime code count — `sdk.ts` is type-only and changing it cannot
 * change the output.
 */
export const SOURCES = [
  join(root, "sdk", "extension", "contract", "guest.ts"),
  join(root, "sdk", "extension", "contract", "sandbox-guest.ts"),
];

export const HASH_MARKER = "// SOURCE-SHA256: ";

/**
 * Fingerprint of the inputs, so a stale artifact is detectable without a build.
 *
 * Line endings are normalised first, and that is not tidiness. `.gitattributes`
 * declares `* text=auto`, so these sources are stored LF and checked out with
 * the platform's own endings — CRLF on Windows. Hashing raw bytes therefore
 * fingerprints the *checkout* rather than the content: an artifact built on one
 * platform reads as stale on the other, with a message telling the reader to
 * rebuild a file that is already correct. Rebuilding produces the identical
 * bundle and the identical complaint.
 */
export function sourceHash() {
  const hash = createHash("sha256");
  for (const file of SOURCES) {
    hash.update(readFileSync(file, "utf8").replace(/\r\n/g, "\n"));
  }
  return hash.digest("hex");
}

export function header(hash) {
  return [
    "// SPDX-License-Identifier: MIT",
    "// GENERATED by `pnpm run build:guest` from sdk/extension/contract/guest.ts.",
    "// Do not edit here. Committed to the repo because Rust embeds it with",
    "// include_str! at compile time, so a fresh clone must build without npm.",
    `${HASH_MARKER}${hash}`,
    "",
  ].join("\n");
}
